services:
  - type: web
    name: arielsql-suite
    env: node
    plan: free
    buildCommand: npm install && npm run build  # or your actual build commands
    startCommand: node arielsql_suite/main.js
    healthCheckPath: /health
    port: 10000
    envVars:
      - key: NODE_ENV
        value: production
      - key: ETH_MAINNET_RPC
        fromSecret: ETH_MAINNET_RPC  # Set this in Render dashboard
      - key: AI_THREAT_API_KEY  
        fromSecret: AI_THREAT_API_KEY  # Set this in Render dashboard
